sudo: required
dist: trusty
language: ruby

before_install:
- gem install asciidoctor -v 1.5.2
- gem install tilt
- sudo pip install git+https://github.com/gitenberg-dev/gitberg
- sudo pip install git+https://github.com/gitenberg-dev/pg-epubmaker
script:
- VERSION=`ruby -e "require 'yaml'; meta = YAML.load_file('metadata.yaml'); puts meta['_version'];"`
- git clone https://github.com/gitenberg-dev/asciidoctor-htmlbook.git
- sudo pip install -r asciidoctor-htmlbook/gitberg-machine/requirements.txt

- /usr/bin/python -c "from gitenberg import travis; travis.build_epub()"
- ebook-convert book.epub book.mobi
- xvfb-run ebook-convert book.epub book.pdf
notifications:
  webhooks:
    urls:
      - https://unglue.it/api/travisci/webhook
    on_success: always
    on_failure: never
    on_start: never
deploy:
  skip_cleanup: true
  provider: releases
  api_key:
    secure: HGOQAgQ2rigkrKlFDW5IbDBwC8HAiW6kMJ/sPAEehxEPANhNXKVTXJMBX+nVXN4CxkRElNy1ZjBS9WNIw+9tLaXYOJcMyRcg0SpieHoPbM7q5EORwUBk9bHSsCSkuneUKgzcarGne1bU8acrVfbh4J73NE2xPBM+Da74YLLOakSKcbRNC2M2U6WWJT6KbYTcl5YFpmXrCdmA/QVJbaEyB/Y0z8tHZXxzXFsEDBHJ2Yli5SnPgKor3fmDXSMReIXhHcLPOiZwirXB11M1jR2f2phk6/G59Cy4j88ILPjYI3rKatoC0vjI/8Q1468aYwxjWA/AyhndXoMjew23iSp4BsZurE4TeQ6y6q+ff+PwLNpn2rogsqos6X9W28dCKylAz7aBN/06YpomNDAHrJvE231ONT5+Ky162NWMzqKZd86h9AHIDGVvhpaHL3xVez+oVqJxIzbzn7PHVHviFfFobY4iVuqnqqdz2ElMWF8RNJhrUK47ouT81kP0jn9kKXgFUZ9PINKixJWCxf78ddVKksqx1OyUyCuxlKHB46VDhbz+greWLdPRdRS+oBIGoWHf7R2BVkLz+gvDh/tW15hf72bGvhr6dLGh4D6ZxzGA6J5KdAqFyRKoAeD7MY3VlrvMRImqPgFi3BNe1qYzxv5kmIYsRgsVun/YbR3Wx6jTJa0=
  file:
    - book.epub
    - book.mobi
    - book.pdf
  on:
    repo: GITenberg/The-Gutenberg-Webster-s-Unabridged-Dictionary-Section-A-and-B_660
    tags: true
addons:
  apt:
    packages:
    - xsltproc
    - xvfb
    - calibre
    - python-pip
    - git
    - python-dev
    - libjpeg-dev
    - libpng-dev
    - libfreetype6
    - libfreetype6-dev
    - zlib1g-dev
    - python-lxml
    - libxml2-dev
    - libxslt1-dev
    - tidy